api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework import urls as rest_urls
from api.views import WorkWithProductSet, Login, WorkWithUserSet

router = DefaultRouter()
router.register('products', WorkWithProductSet)
router.register('users', WorkWithUserSet)
urlpatterns = router.get_urls()
urlpatterns += path('auth/login', Login.as_view()),

my_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import re_path, include

admin.autodiscover()

urlpatterns = [
                  re_path(r'admin/', admin.site.urls),
                  re_path(r'^', include('landing.urls')),
                  re_path(r'^', include('orders.urls')),
                  re_path(r'^api/', include('api.urls')),
                  re_path(r'auth/', include('authentication.urls')),
                  re_path(r'^', include('products.urls')),

              ] + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.contrib import admin
from django.urls import re_path, include

from products import views

admin.autodiscover()

urlpatterns = [
    re_path(r'^product/(?P<product_id>\w+)/$', views.show_product, name='product'),
    re_path(r'^product/(?P<product_id>\w+)/comment/add$', views.add_comment, name='add_comment'),
]

products/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.encoding import smart_text

# Create your models here.
from my_shop import settings


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, default=None, null=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = 'categories'
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return smart_text('Категория: ' + self.name)


class Product(models.Model):
    class Meta:
        db_table = 'products'
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    name = models.CharField(max_length=64, blank=True, default=None, null=True)
    category = models.ForeignKey(ProductCategory, blank=True, null=True,
                                 on_delete=models.NOT_PROVIDED)
    price = models.IntegerField(blank=False, default=None, null=False)
    discount = models.IntegerField(default=0)
    description = models.TextField(blank=True, default=None, null=True)
    short_description = models.TextField(blank=True, default=None, null=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    views = models.IntegerField(default=0)

    def __str__(self):
        return smart_text('Товар: ' + self.name + " Цена:" + str(self.price))


class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, default=None, null=True, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products_images/')
    is_active = models.BooleanField(default=True)
    is_main = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    class Meta:
        verbose_name = 'Image'
        verbose_name_plural = 'Images'

    def __str__(self):
        return smart_text(str(self.id))


class ProductComment(models.Model):
    class Meta:
        db_table = 'comments'

    text = models.TextField(blank=False, null=False, max_length=1024)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)

products/views.py
# from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from django.shortcuts import render, get_object_or_404

# Create your views here.

from django.views.decorators.http import require_POST

from orders.decorators import require_ajax
from products.models import Product, ProductComment


def show_product(request, product_id):
    product = Product.objects.get(id=product_id)
    product.views += 1

    comments = ProductComment.objects.filter(product=product).order_by('-created')
    paginator = Paginator(comments, 2)
    page = request.GET.get('page')
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)
    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()
    if request.is_ajax():
        return render(request, 'products/comments.html', {'comments': comments, 'product_id': product_id})
    product.save(force_update=True)
    return render(request, 'products/product.html', locals())


@login_required
@require_POST
@require_ajax
def add_comment(request, product_id):
    data = request.POST
    ProductComment.objects.create(text=data['text'], user=request.user, product_id=product_id)
    product = get_object_or_404(Product, id=product_id)
    comments = ProductComment.objects.filter(product=product).order_by('-created')
    paginator = Paginator(comments, 2)
    comments = paginator.page(1)
    return render(request, 'products/comments.html', {'comments': comments, 'product_id': product_id})

templates/products/comments.html
{% if comments %}
    {% for comment in comments %}
        <div class="col-sm-12">
            <div class="col-sm-2">
                <div class="thumbnail">
                    <img class="img-responsive user-photo"
                         src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
                </div>
            </div>

            <div class="col-sm-10">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong>{{ comment.user.email }}</strong> <span class="text-muted"
                                                                           style="position: absolute; right: 0;">{{ comment.created }}</span>
                    </div>
                    <div class="panel-body">
                        {{ comment.text }}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}



    <div class="my-pagination col-sm-12">
    <span class="step-links">
        {% if comments.has_previous %}
            <button class="btn btn-link" onclick="loadComments({{ comments.previous_page_number }})"><<</button>
        {% endif %}

        <span class="current">
            Страница {{ comments.number }} из {{ comments.paginator.num_pages }}.
        </span>

        {% if comments.has_next %}
            <button class="btn btn-link"  onclick="loadComments({{ comments.next_page_number }})">>></button>
        {% endif %}
    </span>
    </div>
    <br>



{% else %}
    <div>Никто еще не оставил комментариев</div><br><br>
{% endif %}

templates/products/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                {% for image_item in product.productimage_set.all %}
                    <img src="{{ image_item.image.url }}" class="img-responsive img-product">
                {% endfor %}
                <br>
                <div>
                    <form id="form_buying_product" class="form-inline" action="{% url 'add_to_cart' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>Кол-во: </label>
                            <input type="number" name="count" id="count" value="1" class="form-control form-count"
                                   min="1">
                        </div>


                        <div class="form-group">
                            <button id="submit-btn" type="submit" class="btn btn-success btn-buy"
                                    data-product-id="{{ product_id }}"
                                    data-name="{{ product.name }}"
                                    data-price="{{ product.price }}">Купить
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-6">
                <h1 class="text-center">
                    {{ product.name }}
                </h1>
                <div class="">
                    <p>
                        Price: {{ product.price }}
                    </p>
                </div>
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active">
                        <a href="#description" aria-controls="description" role="tab"
                           data-toggle="tab">Описание</a></li>
                    <li role="presentation">
                        <a href="#delivery" aria-controls="delivery" role="tab" data-toggle="tab">Доставка</a>
                    </li>
                    <li role="presentation">
                        <a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Комментарии</a>
                    </li>

                </ul>

                <!-- Tab panes -->
                <div class="tab-content product-description-tabs">
                    <div role="tabpanel" class="tab-pane active" id="description">
                        {{ product.description }}</div>
                    <div role="tabpanel" class="tab-pane" id="delivery"><h3>
                        Как мы делаем доставку
                    </h3></div>
                    <div role="tabpanel" class="tab-pane" id="messages">

                        <div id="wrapper">
                            {% include "products/comments.html" %}
                        </div>

                        {% if request.user.is_authenticated %}
                            <form method="POST" id="comment">
                                {% csrf_token %}
                                <textarea id="comment_text" maxlength="1024" name="comment_text"
                                          class="form-control comment"
                                          required></textarea>
                                <span class="form-error"></span>
                                <button type="submit" class="btn btn-sm btn-info">Добавить комментарий</button>
                            </form>
                        {% endif %}

                    </div>

                </div>

            </div>

        </div>
    </div>
{% endblock %}