api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework import urls as rest_urls
from api.views import WorkWithProductSet, Login, WorkWithUserSet

router = DefaultRouter()
router.register('products', WorkWithProductSet)
router.register('users', WorkWithUserSet)
urlpatterns = router.get_urls()
urlpatterns += path('auth/login', Login.as_view()),

authentication/urls.py
from django.urls import re_path
from . import views

app_name = 'auth'

urlpatterns = [
    re_path(r'^register/$', views.sign_up, name='register'),
    re_path(r'^login/$', views.sign_in, name='login'),
    re_path(r'^logout/$', views.log_out, name='logout'),
    re_path(r'^verify/(?P<uuid>[a-z0-9\-]+)/', views.verify, name='verify')
]

my_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import re_path, include

admin.autodiscover()

urlpatterns = [
                  re_path(r'admin/', admin.site.urls),
                  re_path(r'^', include('landing.urls')),
                  re_path(r'^', include('orders.urls')),
                  re_path(r'^api/', include('api.urls')),
                  re_path(r'auth/', include('authentication.urls')),
                  re_path(r'^', include('products.urls')),

              ] + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello!</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">

    <!-- Roboto font-family -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400&amp;subset=cyrillic,cyrillic-ext,latin-ext"
          rel="stylesheet">

    <!-- Custom styles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">


</head>
<body>

<div class="wrapper">

    {% include 'navbar.html' %}

    {% block content %}
    {% endblock %}


    {% include 'footer.html' %}
</div>


<!-- JQuery -->
<script src="http://code.jquery.com/jquery-2.0.0.js"></script>

<!-- Bootstrap JS -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<script src="{% static 'js/scripts.js' %}"></script>
<script src="{% static 'js/jquery.cookie.js' %}"></script>
</script>

</body>
</html>

templates/footer.html
<footer class="footer">
    <div class="container">
        <h3>Footer!</h3>
    </div>
</footer>

templates/navbar.html
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-top" xmlns="http://www.w3.org/1999/html">

</nav>

<nav class="navbar navbar-default navbar-main">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">Домой</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header">Nav header</li>
                        <li><a href="#">Separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <div class="basket-container
">
                        <a href="#">Корзина<span id="basket_total_amount"></span><span
                                id="basket_total_count">
                            {% if products_total_count %}
                                ({{ products_total_count }})
                            {% else %}
                                (0)
                            {% endif %}
                        </span></a>
                        <div class="basket-items hidden">
                            <ul class="">
                                {% for k, v in products_in_basket.items %}

                                    <li>{{ v.name }} {{ v.count }} шт.
                                        по {{ v.price }}rub <a href="#"
                                                               class="delete-item"
                                                               data-action="{% url 'remove_from_cart' %}"
                                                               data-product_id="{{ k }}">x</a>
                                    </li>
                                {% endfor %}
                                {% if products_total_count %}
                                    <div class="navbar-total-amount"> Итого: {{ total_amount }}rub<br>
                                        <a href="{% url 'checkout' %}" class="btn btn-success btn-xs">
                                            Оформить заказ
                                        </a>
                                    </div>
                                {% else %}
                                    Корзина пуста
                                {% endif %}
                            </ul>

                        </div>
                    </div>
                </li>


                {% if not request.user.is_authenticated %}

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span
                                class="caret"></span></a>
                        <ul id="login-dp" class="dropdown-menu">
                            <li>
                                <div class="row">
                                    <div class="col-md-12">
                                        <form class="form" role="form" method="post" action="{% url 'auth:login' %}"
                                              accept-charset="UTF-8"
                                              id="login-nav">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <label class="sr-only" for="exampleInputEmail2">Email</label>
                                                <input type="text" class="form-control" name="email"
                                                       id="exampleInputEmail2"
                                                       placeholder="Email" required>
                                            </div>
                                            <div class="form-group">
                                                <label class="sr-only" for="exampleInputPassword2">Password</label>
                                                <input type="password" class="form-control" name="password"
                                                       id="exampleInputPassword2"
                                                       placeholder="Пароль" required>
                                                <div class="help-block text-right"><a href="">Forget the password ?</a>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-primary btn-block">Войти</button>
                                            </div>

                                        </form>
                                    </div>
                                    <div class="bottom text-center">
                                        Нет аккаунта ? <a href="{% url 'auth:register' %}"><b>Регистрация</b></a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li>
                        <div class="logout">
                            <a href="{% url 'auth:logout' %}">Logout</a>
                        </div>
                    </li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>